import {describe, it, expect} from "vitest";
import {partOne} from "./d07-laboratories";
import {readInput} from "../lib/utils";

const input = readInput("y2025/inputs/d07.txt");

const example =
`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe("solutions", () => {
    it('runs day one', () => {
        expect(partOne(example)).toStrictEqual(21);
        expect(partOne(input)).toStrictEqual(1662);
    })
  }
)